module.exports = [
  {
    name: "petal",
    base: "base-light.css",
    vars: "root-petal.css",
    label: "🌸 花瓣 (Petal)",
    accent: "#e8859b",
    bg: "#fdf9fa",
    text: "#333333",
  },
  {
    name: "petal-dark",
    base: "base-dark.css",
    vars: "root-petal-dark.css",
    label: "🔮 花瓣·暗夜",
    accent: "#ffaac8",
    bg: "#332c32",
    hue: 350,
    text: "#eeeeee",
  },
  {
    name: "mist",
    base: "base-light.css",
    vars: "root-mist.css",
    label: "☁️ 雾蓝 (Mist)",
    accent: "#92A8B3",
    bg: "#F2F4F5",
    text: "#333333",
  },
  {
    name: "mist-dark",
    base: "base-dark.css",
    vars: "root-mist-dark.css",
    label: "💠 雾蓝·暗夜",
    accent: "#9bb9d7",
    bg: "#333840",
    hue: 240,
    text: "#eeeeee",
  },
  {
    name: "verdant",
    base: "base-light.css",
    vars: "root-verdant.css",
    label: "🍃 草木 (Verdant)",
    accent: "#A0B0A7",
    bg: "#F2F5F3",
    text: "#333333",
  },
  {
    name: "verdant-dark",
    base: "base-dark.css",
    vars: "root-verdant-dark.css",
    label: "🌲 草木·暗夜",
    accent: "#99b3a3",
    bg: "#202522",
    hue: 160,
    text: "#eeeeee",
  },
  {
    name: "stone",
    base: "base-light.css",
    vars: "root-stone.css",
    label: "🧱 暖石 (Stone)",
    accent: "#B1A49E",
    bg: "#F5F3F1",
    text: "#333333",
  },
  {
    name: "stone-dark",
    base: "base-dark.css",
    vars: "root-stone-dark.css",
    label: "🪨 暖石·暗夜",
    accent: "#dab39b",
    bg: "#33302e",
    text: "#eeeeee",
  },
  {
    name: "ripple",
    base: "base-light.css",
    vars: "root-ripple.css",
    label: "🌊 涟漪 (Ripple)",
    accent: "#5fa8b2",
    bg: "#fcfdfe",
    text: "#333333",
  },
  {
    name: "ripple-dark",
    base: "base-dark.css",
    vars: "root-ripple-dark.css",
    label: "🌊 涟漪·暗夜",
    accent: "#9bd7da",
    bg: "#262d2e",
    text: "#eeeeee",
  },
  {
    name: "ink",
    base: "base-light.css",
    vars: "root-ink.css",
    label: "🖋️ 水墨 (Ink)",
    accent: "#cc584d",
    bg: "#fbfbfb",
    text: "#333333",
  },
  {
    name: "ink-dark",
    base: "base-dark.css",
    vars: "root-ink-dark.css",
    label: "🖋️ 水墨·暗夜",
    accent: "#e26b5f",
    bg: "#242424",
    text: "#eeeeee",
  },
  {
    name: "amber",
    base: "base-light.css",
    vars: "root-amber.css",
    label: "💎 琥珀 (Amber)",
    accent: "#c3874b",
    bg: "#fbf8f6",
    text: "#333333",
  },
  {
    name: "amber-dark",
    base: "base-dark.css",
    vars: "root-amber-dark.css",
    label: "🔥 琥珀·暗夜",
    accent: "#ebaf78",
    bg: "#25201d",
    hue: 45,
    text: "#eeeeee",
  },
  {
    name: "spring",
    base: "base-light.css",
    vars: "root-spring.css",
    label: "🌸 紫语 (Spring)",
    accent: "#A873C4",
    bg: "#fcf9fd",
    text: "#333333",
  },
  {
    name: "spring-dark",
    base: "base-dark.css",
    vars: "root-spring-dark.css",
    label: "🔮 紫语·暗夜",
    accent: "#bfa9f5",
    bg: "#2e2a33",
    text: "#eeeeee",
  },
];
